import pandas as pd
import numpy as np
df = pd.read_csv("data/trends_clean.csv")
print("=" * 55)
print("First 5 rows:")
print("=" * 55)
print(df.head())
print(f"\nDataFrame shape: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"\nAverage score       : {df['score'].mean():.2f}")
print(f"Average num_comments: {df['num_comments'].mean():.2f}")
scores = df["score"].to_numpy()
print("\n" + "=" * 55)
print("Score statistics (NumPy):")
print("=" * 55)
print(f"  Mean              : {np.mean(scores):.2f}")
print(f"  Median            : {np.median(scores):.2f}")
print(f"  Standard deviation: {np.std(scores):.2f}")
print(f"\n  Highest score: {np.max(scores)}")
print(f"  Lowest score : {np.min(scores)}")
category_counts = df["category"].value_counts()
top_category = category_counts.idxmax()
print(f"\nCategory with the most stories: '{top_category}' ({category_counts[top_category]} stories)")

most_commented_idx = df["num_comments"].idxmax()
most_commented = df.loc[most_commented_idx]
print(f"\nMost-commented story:")
print(f"  Title   : {most_commented['title']}")
print(f"  Comments: {int(most_commented['num_comments'])}")
df["engagement"] = df["num_comments"] / (df["score"] + 1)
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score
print("\n" + "=" * 55)
print("New columns added:")
print("=" * 55)
print(df[["title", "score", "num_comments", "engagement", "is_popular"]].head(10))
print(f"\nPopular stories (score > {avg_score:.2f}): {df['is_popular'].sum()} / {len(df)}")
print(f"Average engagement ratio              : {df['engagement'].mean():.4f}")
output_path = "data/trends_analysed.csv"
df.to_csv(output_path, index=False)
print("\n" + "=" * 55)
print(f"✅ Saved enriched dataset to '{output_path}'")
print(f"   Rows: {df.shape[0]} | Columns: {df.shape[1]}")
print("=" * 55)